
[project]
name = "redshift-catalog-curation-assistant"
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
authors = [
    { name = "Luigi Lucas de Carvalho Silva", email = "luigi.lcsilva@gmail.com" }
]
description = "A simple, reproducible and extensible tool to aid in the technical curation of heterogeneous redshift catalogs."
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
    "pyyaml>=6.0",
    "numpy>=1.24",
    "pandas>=2.0",
    "dask[dataframe,distributed]>=2024.1",
    "dask-jobqueue>=0.8",
    "pyarrow>=12.0",
    "astropy>=5.3",
    "fitsio>=1.3",
]

[project.scripts]
redshift-curator = "redshift_catalog_curation_assistant.cli.cli:main"

[project.urls]
"Source Code" = "https://github.com/luigilcsilva/redshift-catalog-curation-assistant"

# On a mac, install optional dependencies with `pip install '.[dev]'` (include the single quotes)
[project.optional-dependencies]
dev = [
    "asv[virtualenv]==0.6.5", # Used to compute performance benchmarks
    "jupyter>=1.0", # Clears output from Jupyter notebooks
    "mypy>=1.8", # Used for static type checking of files
    "pre-commit>=3.5", # Used to run checks before finalizing a git commit
    "pytest>=7.4",
    "pytest-cov>=4.1", # Used to report total code coverage
    "ruff>=0.2.1", # Used for static linting of files
]

[build-system]
requires = [
    "setuptools>=62", # Used to build and package the Python project
    "setuptools_scm>=6.2", # Gets release version from git. Makes it available programmatically
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/redshift_catalog_curation_assistant/_version.py"

[tool.pytest.ini_options]
pythonpath = [
    "src",
]
testpaths = [
    "tests",
    "src",
    "docs",
]
addopts = "--doctest-modules --doctest-glob=*.rst"

[tool.ruff]
line-length = 110
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pep8-naming
    "N",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # docstrings
    "D101",
    "D102",
    "D103",
    "D106",
    "D206",
    "D207",
    "D208",
    "D300",
    "D417",
    "D419",
    # Numpy v2.0 compatibility
    "NPY201",
]
ignore = [
    "UP006", # Allow non standard library generics in type hints
    "UP007", # Allow Union in type hints
    "SIM114", # Allow if with same arms
    "B028", # Allow default warning level
    "SIM117", # Allow nested with
    "UP015", # Allow redundant open parameters
    "UP028", # Allow yield in for loop
]

[tool.ruff.lint.isort]
known-first-party = ["redshift_catalog_curation_assistant"]

[tool.mypy]
python_version = "3.11"
[tool.setuptools.package-data]
redshift_catalog_curation_assistant = ["py.typed"]

[tool.coverage.run]
omit=["src/redshift_catalog_curation_assistant/_version.py"]
