title: 2dFLenS Final Data Release
subtitle: Basic dataset characterization
output_notebook: reports/qa/2dflens.ipynb
generate_html: true
output_html: reports/qa/2dflens.html
input_file: tests/data/curated/2dflens.parquet
input_format: parquet
include_absolute_input_path: false

header_images:
  - url: https://www.linea.org.br/brand/linea-logo-color.svg
    width: 100
    style: "padding: 40px"
  - url: https://cdn2.webdamdb.com/1280_c3PXjCZbPM23.png
    width: 180

summary:
  - "**Original file:** `2dflens_bestredshifts_goodz_withtypesandmags_final.dat.gz`"
  - "**Data obtained from:** https://2dflens.swin.edu.au/data.html"
  - "**Schema:** https://2dflens.swin.edu.au/data.html"
  - "**Reference paper:** https://ui.adsabs.harvard.edu/abs/2016MNRAS.462.4240B"
  - "**Manipulations:** Inserting `survey_name` column."

acknowledgments:
  - This notebook was supported by resources supplied by the Laboratório Interinstitucional de e-Astronomia (LIneA).
  - We acknowledge the use of the 2dFLenS Final Data Release catalog. Additional information about the 2dFLenS Survey can be found on the official survey homepage and in its main article.

plots:
  spatial:
    ra_column: RA
    dec_column: Dec
    footprints:
      - path: tests/data/curves/rubin_dp2_footprint.csv
        label: Rubin DP2 footprint
        color: red
      - path: tests/data/curves/rubin_footprint.csv
        label: Rubin footprint
        color: orange
  redshift:
    column: z
    range: [-0.05, 1]
    bins: 50
  quality:
    column: qual
    description: |
      | Q | Description |
      |---|---|
      | 1 | Unknown redshift |
      | 2 | Possible but uncertain redshift |
      | 3 | Probably correct redshift derived from noisy data or fewer spectral features |
      | 4 | Secure redshift confirmed by multiple spectral features |
      | 6 | Spectrum clearly not extragalactic |

      **Source**: https://ui.adsabs.harvard.edu/abs/2016MNRAS.462.4240B/abstract
