title: 2MRS V240
subtitle: Basic dataset characterization
output_notebook: reports/qa/2mrs.ipynb
generate_html: true
output_html: reports/qa/2mrs.html
input_file: reports/curated/2mrs.parquet
input_format: parquet
include_absolute_input_path: false

summary:
  - "**Original files:** `2mrs_1175_done.fits` and `2mrs_extra_done.fits`"
  - "**Data obtained from:** http://tdc-www.harvard.edu/2mrs/"
  - "**Schema:** http://tdc-www.harvard.edu/2mrs/2mrs_readme.html"
  - "**Reference paper:** https://ui.adsabs.harvard.edu/abs/2012ApJS..199...26H/abstract"
  - "**Manipulations:** Concatenation of files. Computation of redshift columns from the velocity columns. Inserting the `survey_name` column."

acknowledgments:
  - This work uses data products produced by the OIR Telescope Data Center, supported by the Smithsonian Astrophysical Observatory.

plots:
  spatial:
    ra_column: RA
    dec_column: DEC
  redshift:
    column: redshift
    range: [-0.05, 0.3]
    bins: 50
  redshift_error:
    column: redshift_err
    range: [-0.00005, 0.0005]
    bins: 50
