input_file: tests/data/raw/2dflens_sample.dat.gz
output_dir: tests/data/prepared/2dflens.parquet
output_mode: single
overwrite: true
part_prefix: 2dflens

column_names:
  - RA
  - Dec
  - z
  - qual
  - target
  - umag
  - gmag
  - rmag
  - imag
  - zmag
  - w1mag
