input_file: tests/data/raw/C3R2-DR3-18june2021.txt
output_dir: tests/data/prepared/c3r2_dr3.parquet
output_mode: single
overwrite: true
part_prefix: c3r2_dr3

column_names:
  - ID
  - RAh
  - RAm
  - RAs
  - DEd_raw
  - DEm
  - DEs
  - Mask
  - Slit
  - imag
  - zspec
  - Qual
  - Instrument
  - spec1dfile
