input_file: tests/data/prepared/2mrs.parquet
survey_name: 2MRS
unique_limit: 10

column_patterns:
  ra:
    - "^RA$"
  dec:
    - "^DEC$"
  redshift:
    - "^V$"
  redshift_error:
    - "^EV$"
  quality:
    - "^FLAGS$"
  id:
    - "^TMID$"
    - "^CATID$"
  object_type:
    - "^TYPE$"
    - "^TYPESRC$"
