input_file: tests/data/raw/2dfgrs_sample.idz.gz
survey_name: 2DFGRS
unique_limit: 10

column_names:
  - serial
  - spectra
  - name
  - UKST
  - ra_b1950_h
  - ra_b1950_m
  - ra_b1950_s
  - dec_b1950_d
  - dec_b1950_m
  - dec_b1950_s
  - ra_j2000_h
  - ra_j2000_m
  - ra_j2000_s
  - dec_j2000_d
  - dec_j2000_m
  - dec_j2000_s
  - BJG
  - BJSEL
  - BJG_OLD
  - BJSELOLD
  - GALEXT
  - SB_BJ
  - SR_R
  - z
  - z_helio
  - obsrun
  - quality
  - abemma
  - Z_ABS
  - KBESTR
  - R_CRCOR
  - Z_EMI
  - NMBEST
  - SNR
  - ETA_TYPE

column_patterns:
  ra:
    - "^ra_j2000_"
  dec:
    - "^dec_j2000_"
  redshift:
    - "^z$"
    - "^z_helio$"
  quality:
    - "^quality$"
  id:
    - "^serial$"
    - "^name$"
  object_type:
    - "^ETA_TYPE$"
