input_file: tests/data/raw/6dfgs_sample.csv.gz
survey_name: 6DFGS
unique_limit: 10

column_patterns:
  ra:
    - "^OBSRA$"
  dec:
    - "^OBSDEC$"
  redshift:
    - "^Z$"
    - "^Z_HELIO$"
  quality:
    - "^QUALITY$"
  id:
    - "^SPECID$"
    - "^TARGETID$"
