input_file: tests/data/prepared/2dflens.parquet
output_dir: tests/data/curated/2dflens.parquet
output_mode: single
overwrite: true
part_prefix: 2dflens

column_selection:
  - RA
  - Dec
  - z
  - qual
  - target
  - umag
  - gmag
  - rmag
  - imag
  - zmag
  - w1mag
  - survey_name

coordinates:
  ra_column: RA
  dec_column: Dec

redshift:
  column: z
  invalid_policy: keep

transformations:
  - type: add_constant_column
    name: survey_name
    value: 2DFLENS
