input_file: tests/data/prepared/c3r2_dr3.parquet
output_dir: tests/data/curated/c3r2_dr3.parquet
output_mode: single
overwrite: true
part_prefix: c3r2_dr3

column_selection:
  - ID
  - RAh
  - RAm
  - RAs
  - DE_sign
  - DEd
  - DEm
  - DEs
  - ra
  - dec
  - Mask
  - Slit
  - imag
  - zspec
  - Qual
  - Instrument
  - spec1dfile
  - survey_name

coordinates:
  ra_column: ra
  dec_column: dec

redshift:
  column: zspec

transformations:
  - type: signed_value_sign
    input_column: DEd_raw
    output_column: DE_sign
  - type: absolute_value
    input_column: DEd_raw
    output_column: DEd
    dtype: int64
  - type: ra_hms_to_degrees
    output_column: ra
    hours: RAh
    minutes: RAm
    seconds: RAs
  - type: dec_dms_to_degrees
    output_column: dec
    degrees: DEd_raw
    arcminutes: DEm
    arcseconds: DEs
  - type: replace_values
    column: imag
    replacements:
      - from: -1.0
        to:
  - type: replace_values
    column: spec1dfile
    replacements:
      - from: -1
        to:
      - from: "-1"
        to:
  - type: add_constant_column
    name: survey_name
    value: C3R2_DR3
